repos:
-   repo: local
    hooks:
    -   id: rn-story-mode
        name: rn-story-mode
        entry: shared/ios/Keybase/git-hook
        language: script
        files: shared/ios/Keybase/Storybook.m
    -   id: eslint
        name: eslint
        entry: shared/node_modules/.bin/eslint
        language: node
        files: \.(js|ts|tsx)$
        args: [
            '--quiet',
            '--resolve-plugins-relative-to shared'
        ]
    -   id: prettier
        name: prettier
        entry: shared/node_modules/.bin/prettier --write
        language: node
        files: \.(js|ts|tsx)$
-   repo: https://github.com/keybase/pre-commit-golang.git
    rev: 3dc8c863835adfd2ab60c5eaf291c0f349118d3a
    hooks:
    -   id: go-fmt
    -   id: go-vet
        files: 'go/.*\.go$'
    -   id: go-vet
        name: 'go vet tuxbot'
        files: 'packaging/linux/tuxbot/bot/docker-cleanup/.*\.go$'
    -   id: go-lint
