repos:
-   repo: local
    hooks:
    -   id: rn-story-mode
        name: rn-story-mode
        entry: shared/ios/Keybase/git-hook
        language: script
        files: shared/ios/Keybase/Storybook.m
    -   id: eslint
        name: eslint
        entry: shared/node_modules/.bin/eslint
        language: node
        files: \.(js|ts|tsx)$
        args: [
            '--quiet',
            '--resolve-plugins-relative-to shared'
        ]
    -   id: prettier
        name: prettier
        entry: shared/node_modules/.bin/prettier --write
        language: node
        files: \.(js|ts|tsx)$
-   repo: https://github.com/keybase/pre-commit-golang.git
    rev: 1797c2bce4b8e8346a63091ab150fb66ea1606c8
    hooks:
    -   id: go-fmt
    -   id: go-vet
    -   id: go-lint
